# chat messages
chat:
  enabled: true
  nickname_color: "#31adc9"
  separator: " > "
  separator_color: "#ffffff"

# join messages - [+] player
join:
  enabled: true
  plus_color: "#28ff03"

# leave messages - [-] player
leave:
  enabled: true
  minus_color: "#ff162a"
